version = 1

[[analyzers]]
name = "shell"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "python"

[analyzers.meta]
runtime_version = "3.x.x"

[[analyzers]]
name = "docker"

[[transformers]]
name = "ruff"

test_patterns = ["test/**"]

[[analyzers]]
name = "test-coverage"
