site_name: Kamihi documentation
site_url: https://kamihi-dev.github.io/kamihi/
site_description: |
  Documentation for Kamihi, a Python framework for rapid Telegram bot development and management
site_author: kiinami
repo_url: https://github.com/kamihi-dev/kamihi
repo_name: kamihi-dev/kamihi

nav:
  - Home: index.md
  #  - Tutorials:
  #  - "How-to guides":
  - Reference:
      - "API Reference": reference/api.md
#  - "Explanation":

theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight

plugins:
  - search

extra:
  generator: false
