name: Release

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    outputs:
      REVISION: ${{ env.REVISION }}
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          token: "${{ secrets.PAT }}"
          fetch-depth: 0
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@0.24.0
        with:
          github_token: ${{ secrets.PAT }}
          changelog_increment_filename: body.md
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: "body.md"
          tag_name: ${{ env.REVISION }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

  docs:
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          token: "${{ secrets.PAT }}"
          fetch-depth: 0
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install dependencies
        run: uv sync --group docs
      - name: Build site and deploy
        run: uv run mike deploy --push --update-aliases ${{ needs.bump-version.outputs.REVISION }} latest
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      - name: Set latest
        run: uv run mike set-default --push latest
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
