name: Release

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Create release"
    outputs:
      REVISION: ${{ env.REVISION }}
    steps:
      - name: Check out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          token: "${{ secrets.PAT }}"
          fetch-depth: 0
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@5b0848cd060263e24602d1eba03710e056ef7711 # 0.24.0
        with:
          github_token: ${{ secrets.PAT }}
          changelog_increment_filename: body.md
      - name: Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        with:
          body_path: "body.md"
          tag_name: ${{ env.REVISION }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

  docs:
    runs-on: ubuntu-latest
    needs: bump-version
    name: "Build and deploy documentation"
    steps:
      - name: Check out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          token: "${{ secrets.PAT }}"
          fetch-depth: 0
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Install uv
        uses: astral-sh/setup-uv@6b9c6063abd6010835644d4c2e1bef4cf5cd0fca # v6
      - name: Install dependencies
        run: uv sync --group docs
      - name: Build site and deploy
        run: uv run mike deploy --push --update-aliases ${{ needs.bump-version.outputs.REVISION }} latest
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      - name: Set latest
        run: uv run mike set-default --push latest
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
